// GENERATED by bin/sync.ts — do not edit by hand.
// Source: shared/hooks/*.ts
// Each hook exports a default function. The composed plugin re-exports them
// under unique keys for OpenCode's plugin loader.
import type { Plugin } from "@opencode-ai/plugin"

import _hook_0 from "../../shared/hooks/block-git-add-all.ts"
import _hook_1 from "../../shared/hooks/block-main-push.ts"
import _hook_2 from "../../shared/hooks/check-secrets.ts"
import _hook_3 from "../../shared/hooks/require-active-ticket.ts"
import _hook_4 from "../../shared/hooks/validate-branch-name.ts"

const hooks = {
  "block-git-add-all": _hook_0,
  "block-main-push": _hook_1,
  "check-secrets": _hook_2,
  "require-active-ticket": _hook_3,
  "validate-branch-name": _hook_4,
}

export const ApexyardHooks: Plugin = async (ctx) => {
  const exported: Record<string, any> = {}
  for (const [name, hook] of Object.entries(hooks)) {
    const result = await hook(ctx)
    if (result && typeof result === "object") {
      for (const [event, handler] of Object.entries(result)) {
        if (typeof handler === "function") {
          exported[event] = exported[event] || []
          exported[event].push({ name, handler })
        }
      }
    }
  }
  return exported
}

export default ApexyardHooks
