#!/usr/bin/env bash
# GENERATED by bin/sync.ts — do not edit by hand.
# Codex hook wrapper for: block-git-add-all
# Reads JSON from stdin (Codex hook protocol) and shells out to the canonical
# TypeScript implementation in shared/hooks/block-git-add-all.ts.
set -euo pipefail
PAYLOAD=$(cat)
PAYLOAD_FILE=$(mktemp)
echo "$PAYLOAD" > "$PAYLOAD_FILE"
trap 'rm -f "$PAYLOAD_FILE"' EXIT
exec bun run "shared/hooks/block-git-add-all.ts" "$PAYLOAD_FILE"
