#!/usr/bin/env bash
# GENERATED by bin/sync.ts — do not edit by hand.
# Codex hook wrapper for: block-private-refs-in-public-repos
# Reads JSON from stdin (Codex hook protocol) and shells out to the canonical
# TypeScript implementation in shared/hooks/block-private-refs-in-public-repos.ts.
set -euo pipefail
PAYLOAD=$(cat)
PAYLOAD_FILE=$(mktemp)
echo "$PAYLOAD" > "$PAYLOAD_FILE"
trap 'rm -f "$PAYLOAD_FILE"' EXIT
exec bun run "shared/hooks/block-private-refs-in-public-repos.ts" "$PAYLOAD_FILE"
