#!/usr/bin/env bash
# GENERATED by bin/sync.ts — do not edit by hand.
# Codex hook wrapper for: onboarding-check
# Reads JSON from stdin (Codex hook protocol) and shells out to the canonical
# TypeScript implementation in shared/hooks/onboarding-check.ts.
set -euo pipefail
PAYLOAD=$(cat)
PAYLOAD_FILE=$(mktemp)
echo "$PAYLOAD" > "$PAYLOAD_FILE"
trap 'rm -f "$PAYLOAD_FILE"' EXIT
exec bun run "shared/hooks/onboarding-check.ts" "$PAYLOAD_FILE"
